#
# Makefile for Invensense inv-mpu-iio device.
#

obj-$(CONFIG_INV_MPU_IIO) += inv-mpu-iio.o

inv-mpu-iio-objs := inv_mpu_core.o inv_mpu_ring.o inv_mpu_trigger.o inv_mpu_misc.o inv_mpu3050_iio.o dmpDefaultMPU6050.o inv_slave_compass.o inv_slave_pressure.o

